global using System;
global using System.Collections.Generic;
global using UnityEngine;
global using UnityEngine.UI;
global using Cysharp.Threading.Tasks;
global using DG.Tweening;
global using Text = TMPro.TextMeshProUGUI;
global using Random = UnityEngine.Random;
global using Debug = UnityEngine.Debug;
global using Cts = System.Threading.CancellationTokenSource;
global using Ct = System.Threading.CancellationToken;